add tests for afex and more
easystats/performance pull request #264
Opened 2021-04-12 06:38 UTC by mattansb

I'll be working here on adding support for `afex_aov`:

- [ ] normality
  - [ ] also fix in `see` (need to store residuals in object)
  - [ ] also for multivariate in general
- [ ] heteroskedasticity
  - [ ] also for multivariate in general?
- [ ] sphericity
  - [ ] also for multivariate in general w/ `car`?

2021-04-17 13:48 UTC, strengejacke requested changes

2021-04-17 13:48 UTC, strengejacke commented on R/check_sphericity.R
> +check_sphericity.default <- function(x, ...) {
I would use `class(X)[1]`, because some model objects inherit from multiple classes.

2021-04-18 05:29 UTC, mattansb commented
``` r
library(afex)
library(performance)

data(obk.long, package = "afex")

obk.long$treatment <- as.character(obk.long$treatment)

aM <- aov_car(value ~ treatment * gender + Error(id/(phase*hour)), 
              data = obk.long)

aW <- aov_car(value ~ Error(id/(phase*hour)), 
              data = obk.long)

aB <- aov_car(value ~ treatment * gender + Error(id), 
              data = obk.long)

check_collinearity(aM)
#> All predictors have been centered (factors with contr.sum(), numerics with scale())
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>                         Term  VIF Increased SE Tolerance
#>                    treatment 1.04         1.02      0.96
#>                       gender 1.07         1.04      0.93
#>                        phase 1.15         1.07      0.87
#>                         hour 1.33         1.15      0.75
#>             treatment:gender 1.07         1.04      0.93
#>              treatment:phase 1.20         1.10      0.83
#>                 gender:phase 1.15         1.07      0.87
#>               treatment:hour 1.45         1.20      0.69
#>                  gender:hour 1.33         1.15      0.75
#>                   phase:hour 1.77         1.33      0.56
#>       treatment:gender:phase 1.20         1.10      0.83
#>        treatment:gender:hour 1.45         1.20      0.69
#>         treatment:phase:hour 2.09         1.45      0.48
#>            gender:phase:hour 1.77         1.33      0.56
#>  treatment:gender:phase:hour 2.09         1.45      0.48

check_collinearity(aW)
#> All predictors have been centered (factors with contr.sum(), numerics with scale())
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>        Term  VIF Increased SE Tolerance
#>       phase 1.00         1.00      1.00
#>        hour 1.00         1.00      1.00
#>  phase:hour 1.00         1.00      1.00

check_collinearity(aB)
#> All predictors have been centered (factors with contr.sum(), numerics with scale())
#> # Check for Multicollinearity
#> 
#> Low Correlation
#> 
#>              Term  VIF Increased SE Tolerance
#>         treatment 1.04         1.02      0.96
#>            gender 1.07         1.04      0.93
#>  treatment:gender 1.07         1.04      0.93



check_normality(aM)
#> OK: residuals appear as normally distributed (p = 0.205).
check_normality(aW)
#> OK: residuals appear as normally distributed (p = 0.550).
check_normality(aB)
#> OK: residuals appear as normally distributed (p = 0.735).



# check_homogeneity(aW) # fail - no between groups
check_homogeneity(aM)
#> OK: Variances in each of the groups are the same (Levene's Test, p = 0.350).
check_homogeneity(aB)
#> OK: Variances in each of the groups are the same (Levene's Test, p = 0.350).



check_sphericity(aM)
#> Warning: Sphericity violated for: 
#>  - hour (p = 0.008)
#>  - treatment:hour (p = 0.008)
#>  - gender:hour (p = 0.008)
#>  - treatment:gender:hour (p = 0.008).
check_sphericity(aW)
#> Warning: Sphericity violated for: 
#>  - hour (p < .001)
#>  - phase:hour (p = 0.027).
# check_sphericity(aB) # fail - no withing conditions
```

<sup>Created on 2021-04-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

2021-04-18 05:32 UTC, mattansb commented
@strengejacke What do you think? Any changes needed?

(I also fixed the qqplot in see to work)

2021-04-19 18:22 UTC, strengejacke requested changes

2021-04-19 18:22 UTC, strengejacke commented on R/check_homogeneity.R
> +        capture.output(p <- check_normality(x))
please add `utils::`

2021-04-19 20:00 UTC, strengejacke requested changes

2021-04-19 20:00 UTC, strengejacke commented on R/check_collinearity.R
> +  contrs <- lapply(is_fac, function(...) contr.sum)[is_fac]
need to change to `stats::contr.sum` here.

2021-04-20 06:52 UTC, mattansb commented
Anything else?

If not will add some tests and merge $_$

2021-04-20 07:41 UTC, strengejacke commented
![picard_make_it_so](https://user-images.githubusercontent.com/26301769/115357062-89a2bf00-a1bc-11eb-9b9f-e2f6af18d69d.jpg)

2021-04-20 07:49 UTC, IndrajeetPatil commented
All checks are still failing because they can't find `afex` in `Imports`, so I guess there is a remaining instance where `afex` is not being used conditionally.

2021-04-20 07:57 UTC, strengejacke commented
This branch is not in line with master. Please remove all `@importFrom` directives.

2021-04-20 07:58 UTC, strengejacke requested changes

2021-04-20 07:58 UTC, strengejacke commented on R/check_collinearity.R
> +#' @importFrom insight find_response get_data
please remove all `importFrom`, as was done in master...

2021-04-20 07:58 UTC, strengejacke commented on R/check_sphericity.R
> +#' @importFrom insight print_color format_p
Here as well (remove importFrom)

2021-04-20 14:45 UTC, strengejacke approved these changes

2021-04-21 06:12 UTC, merged